# Generated by Django 4.2.11 on 2026-06-30 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='字典类型编码')),
                ('name', models.CharField(max_length=100, verbose_name='字典类型名称')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '字典类型',
                'verbose_name_plural': '字典类型',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.TextField(blank=True, default='', verbose_name='配置值')),
                ('value_type', models.CharField(default='string', max_length=30, verbose_name='值类型')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('is_public', models.BooleanField(default=False, verbose_name='前端可见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100, verbose_name='模块')),
                ('action', models.CharField(max_length=100, verbose_name='动作')),
                ('method', models.CharField(blank=True, default='', max_length=16, verbose_name='请求方法')),
                ('request_path', models.CharField(blank=True, default='', max_length=255, verbose_name='请求路径')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('success', models.BooleanField(default=True, verbose_name='是否成功')),
                ('detail', models.TextField(blank=True, default='', verbose_name='详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module', 'action'], name='system_oper_module_d8fe22_idx'), models.Index(fields=['operator'], name='system_oper_operato_10e91f_idx'), models.Index(fields=['-created_at'], name='system_oper_created_9428c1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='菜单名称')),
                ('path', models.CharField(blank=True, default='', max_length=255, verbose_name='路由路径')),
                ('component', models.CharField(blank=True, default='', max_length=255, verbose_name='前端组件')),
                ('icon', models.CharField(blank=True, default='', max_length=64, verbose_name='图标')),
                ('permission_code', models.CharField(blank=True, default='', max_length=100, verbose_name='权限标识')),
                ('menu_type', models.CharField(choices=[('directory', '目录'), ('menu', '菜单'), ('button', '按钮')], default='menu', max_length=20, verbose_name='类型')),
                ('visible', models.BooleanField(default=True, verbose_name='是否显示')),
                ('keep_alive', models.BooleanField(default=False, verbose_name='是否缓存')),
                ('order_num', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='system.menu', verbose_name='父级菜单')),
                ('roles', models.ManyToManyField(blank=True, related_name='system_menus', to='auth.group', verbose_name='角色')),
            ],
            options={
                'verbose_name': '系统菜单',
                'verbose_name_plural': '系统菜单',
                'ordering': ['order_num', 'id'],
                'indexes': [models.Index(fields=['parent', 'order_num'], name='system_menu_parent__0da89b_idx'), models.Index(fields=['path'], name='system_menu_path_470480_idx'), models.Index(fields=['is_active', 'visible'], name='system_menu_is_acti_9a8f83_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='用户名')),
                ('success', models.BooleanField(default=False, verbose_name='是否成功')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, default='', max_length=512, verbose_name='User-Agent')),
                ('message', models.CharField(blank=True, default='', max_length=255, verbose_name='结果说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_login_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '登录日志',
                'verbose_name_plural': '登录日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['username'], name='system_logi_usernam_8218eb_idx'), models.Index(fields=['success'], name='system_logi_success_cf939c_idx'), models.Index(fields=['-created_at'], name='system_logi_created_ffe3f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='DictionaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='显示文本')),
                ('value', models.CharField(max_length=100, verbose_name='字典值')),
                ('order_num', models.IntegerField(default=0, verbose_name='排序')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('dict_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='system.dictionarytype', verbose_name='字典类型')),
            ],
            options={
                'verbose_name': '字典项',
                'verbose_name_plural': '字典项',
                'ordering': ['order_num', 'id'],
                'unique_together': {('dict_type', 'value')},
            },
        ),
    ]
