# Generated by Django 6.0.2 on 2026-03-03 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeritageSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='文物名称')),
                ('sip_code', models.CharField(max_length=50, unique=True, verbose_name='四普编号')),
                ('category', models.CharField(choices=[('GYZ', '古遗址'), ('GMZ', '古墓葬'), ('GJZ', '古建筑'), ('SKT', '石窟寺及石刻'), ('JDJW', '近现代重要史迹及代表性建筑'), ('QT', '其他')], max_length=10, verbose_name='类别')),
                ('level', models.CharField(choices=[('GB', '国保'), ('SB', '省保'), ('XB', '县/市保'), ('DS', '一般不可移动')], max_length=10, verbose_name='保护级别')),
                ('address', models.CharField(max_length=500, verbose_name='详细地址')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('description', models.TextField(help_text='对比三普的变化情况', verbose_name='现状描述')),
                ('manager', models.CharField(max_length=100, verbose_name='管理责任单位/人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '不可移动文物档案',
                'verbose_name_plural': '不可移动文物档案',
            },
        ),
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspect_time', models.DateTimeField(auto_now_add=True, verbose_name='巡查时间')),
                ('is_normal', models.BooleanField(default=True, verbose_name='是否正常')),
                ('issue_details', models.TextField(blank=True, null=True, verbose_name='发现问题')),
                ('photo', models.ImageField(blank=True, upload_to='inspections/%Y/%m/', verbose_name='现场拍照')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='巡查员')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.heritagesite', verbose_name='巡查对象')),
            ],
            options={
                'verbose_name': '巡查登记存档',
                'verbose_name_plural': '巡查登记存档',
            },
        ),
        migrations.CreateModel(
            name='ProjectAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, verbose_name='建设项目名称')),
                ('is_in_protection_zone', models.BooleanField(default=False, verbose_name='是否在保护范围内')),
                ('is_in_control_zone', models.BooleanField(default=False, verbose_name='是否在建控地带内')),
                ('audit_opinion', models.TextField(verbose_name='核查意见')),
                ('status', models.CharField(choices=[('Pending', '待审'), ('Pass', '通过'), ('Reject', '驳回')], max_length=20, verbose_name='审核状态')),
                ('file_archive', models.FileField(blank=True, upload_to='projects/docs/', verbose_name='附件存档')),
                ('related_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.heritagesite', verbose_name='涉及文物')),
            ],
            options={
                'verbose_name': '工程建设核查',
                'verbose_name_plural': '工程建设核查',
            },
        ),
    ]
