# Generated by Django 6.0.2 on 2026-03-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20260303_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritagesite',
            name='control_zone',
            field=models.TextField(blank=True, verbose_name='建控地带坐标集合'),
        ),
        migrations.AddField(
            model_name='heritagesite',
            name='protection_zone',
            field=models.TextField(blank=True, help_text='请输入经纬度序列JSON', verbose_name='保护范围坐标集合'),
        ),
        migrations.AddField(
            model_name='projectaudit',
            name='project_lat',
            field=models.FloatField(default=0.0, verbose_name='项目纬度'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectaudit',
            name='project_lon',
            field=models.FloatField(default=0.0, verbose_name='项目经度'),
            preserve_default=False,
        ),
    ]
