# Generated by Django 6.0.2 on 2026-03-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_heritagesite_control_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heritagesite',
            name='control_zone',
            field=models.TextField(blank=True, null=True, verbose_name='建控地带坐标集合'),
        ),
        migrations.AlterField(
            model_name='heritagesite',
            name='protection_zone',
            field=models.TextField(blank=True, help_text='请输入经纬度序列JSON', null=True, verbose_name='保护范围坐标集合'),
        ),
    ]
