# Generated by Django 6.0.2 on 2026-03-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_heritagesite_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heritagesite',
            name='category',
            field=models.CharField(choices=[('GYZ', '古文化遗址'), ('GMZ', '古墓葬'), ('GJZ', '古建筑'), ('SKT', '石窟寺及石刻'), ('JDJW', '近现代重要史迹及代表性建筑'), ('QT', '其他')], max_length=10, verbose_name='类别'),
        ),
    ]
