# Generated by Django 6.0.2 on 2026-03-03 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_heritagesite_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_changed_password', models.BooleanField(default=False, verbose_name='是否已修改密码')),
                ('first_login_at', models.DateTimeField(blank=True, null=True, verbose_name='首次登录时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户密码修改记录',
                'verbose_name_plural': '用户密码修改记录',
            },
        ),
    ]
