# Generated by Django 6.0.2 on 2026-03-04 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectaudit',
            options={'ordering': ['-received_date'], 'verbose_name': '项目管理', 'verbose_name_plural': '项目管理'},
        ),
        migrations.AddField(
            model_name='projectaudit',
            name='application_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上报日期'),
        ),
        migrations.AddField(
            model_name='projectaudit',
            name='application_report',
            field=models.FileField(blank=True, upload_to='projects/applications/', verbose_name='上报申请报告'),
        ),
        migrations.AddField(
            model_name='projectaudit',
            name='archive_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='归档编号'),
        ),
        migrations.AddField(
            model_name='projectaudit',
            name='archived_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='归档日期'),
        ),
        migrations.AddField(
            model_name='projectaudit',
            name='bureau_approval_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='市局批复日期'),
        ),
        migrations.AddField(
            model_name='projectaudit',
            name='bureau_approval_reply',
            field=models.FileField(blank=True, upload_to='projects/bureau_replies/', verbose_name='市文物局复函'),
        ),
        migrations.AddField(
            model_name='projectaudit',
            name='bureau_opinion',
            field=models.TextField(blank=True, verbose_name='市局审批意见'),
        ),
        migrations.AddField(
            model_name='projectaudit',
            name='inquiry_letter',
            field=models.FileField(blank=True, help_text='支持PDF或DOCX格式', upload_to='projects/inquiry_letters/', verbose_name='项目方查询函'),
        ),
        migrations.AddField(
            model_name='projectaudit',
            name='ovital_kml_file',
            field=models.FileField(blank=True, upload_to='projects/kml_files/', verbose_name='奥维KML文件'),
        ),
        migrations.AddField(
            model_name='projectaudit',
            name='ovital_query_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='奥维查询日期'),
        ),
        migrations.AddField(
            model_name='projectaudit',
            name='ovital_query_record',
            field=models.TextField(blank=True, help_text='记录奥维地图查询情况', verbose_name='奥维查询记录'),
        ),
        migrations.AddField(
            model_name='projectaudit',
            name='project_reply_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='回函日期'),
        ),
        migrations.AddField(
            model_name='projectaudit',
            name='project_reply_letter',
            field=models.FileField(blank=True, upload_to='projects/project_replies/', verbose_name='回函项目方'),
        ),
        migrations.AddField(
            model_name='projectaudit',
            name='project_unit',
            field=models.CharField(blank=True, max_length=200, verbose_name='项目单位'),
        ),
        migrations.AddField(
            model_name='projectaudit',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='接收日期'),
        ),
        migrations.AddField(
            model_name='projectaudit',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='projectaudit',
            name='site_survey_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='现场勘察日期'),
        ),
        migrations.AddField(
            model_name='projectaudit',
            name='site_survey_photos',
            field=models.FileField(blank=True, help_text='可上传照片压缩包', upload_to='projects/survey_photos/', verbose_name='现场勘察照片'),
        ),
        migrations.AddField(
            model_name='projectaudit',
            name='site_survey_record',
            field=models.TextField(blank=True, help_text='记录现场勘察情况', verbose_name='现场勘察记录'),
        ),
        migrations.AddField(
            model_name='projectaudit',
            name='survey_conclusion',
            field=models.TextField(blank=True, help_text='项目是否涉及文物的最终结论', verbose_name='勘察结论'),
        ),
        migrations.AddField(
            model_name='projectaudit',
            name='workflow_status',
            field=models.CharField(choices=[('received', '已接收查询函'), ('ovital_checked', '奥维查询完成'), ('site_surveyed', '现场勘察完成'), ('application_submitted', '已上报市文物局'), ('bureau_approved', '市局审批完成'), ('replied_to_project', '已回函项目方'), ('archived', '归档完成')], default='received', max_length=30, verbose_name='工作流状态'),
        ),
        migrations.AlterField(
            model_name='projectaudit',
            name='audit_opinion',
            field=models.TextField(blank=True, verbose_name='核查意见'),
        ),
        migrations.AlterField(
            model_name='projectaudit',
            name='project_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='项目纬度'),
        ),
        migrations.AlterField(
            model_name='projectaudit',
            name='project_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='项目经度'),
        ),
        migrations.AlterField(
            model_name='projectaudit',
            name='related_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.heritagesite', verbose_name='涉及文物'),
        ),
        migrations.AlterField(
            model_name='projectaudit',
            name='status',
            field=models.CharField(choices=[('Pending', '待审'), ('Pass', '通过'), ('Reject', '驳回')], default='Pending', max_length=20, verbose_name='审核状态'),
        ),
    ]
