# Generated by Django 6.0.3 on 2026-03-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_projectaudit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectaudit',
            name='construction_content',
            field=models.TextField(default='', verbose_name='工程建设内容与地址'),
        ),
        migrations.AddField(
            model_name='projectaudit',
            name='project_coordinates',
            field=models.TextField(default='', verbose_name='项目选址的经纬度坐标'),
        ),
        migrations.AddField(
            model_name='projectaudit',
            name='project_scale',
            field=models.CharField(default='', max_length=500, verbose_name='项目建设的规模'),
        ),
    ]
