# Generated by Django 6.0.3 on 2026-03-05 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0011_coordinate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserManagementAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('add_user', '创建用户'), ('change_user', '修改用户'), ('delete_user', '删除用户'), ('add_group', '创建用户组'), ('change_group', '修改用户组'), ('delete_group', '删除用户组'), ('add_to_group', '添加用户到组'), ('remove_from_group', '从组移除用户')], max_length=20, verbose_name='操作类型')),
                ('details', models.TextField(blank=True, verbose_name='操作详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_actions', to=settings.AUTH_USER_MODEL, verbose_name='操作员')),
                ('target_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='目标用户组')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_logs', to=settings.AUTH_USER_MODEL, verbose_name='目标用户')),
            ],
            options={
                'verbose_name': '用户管理审计日志',
                'verbose_name_plural': '用户管理审计日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_userma_created_f3a013_idx'), models.Index(fields=['operator'], name='core_userma_operato_b79ff4_idx'), models.Index(fields=['action'], name='core_userma_action_1f0bae_idx')],
            },
        ),
    ]
