# Generated by Django 6.0.2 on 2026-03-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_usermanagementaudit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectionrecord',
            options={'ordering': ['-inspect_time'], 'verbose_name': '巡查登记存档', 'verbose_name_plural': '巡查登记存档'},
        ),
        migrations.AddField(
            model_name='inspectionrecord',
            name='latitude',
            field=models.FloatField(blank=True, help_text='巡查时的GPS纬度', null=True, verbose_name='巡查纬度'),
        ),
        migrations.AddField(
            model_name='inspectionrecord',
            name='longitude',
            field=models.FloatField(blank=True, help_text='巡查时的GPS经度', null=True, verbose_name='巡查经度'),
        ),
    ]
