# Generated by ChatGPT on 2026-06-29

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_immovableheritage_coord_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandUseProjectApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255, verbose_name='用地项目名称')),
                ('company_name', models.CharField(max_length=255, verbose_name='企业单位名称')),
                ('incoming_doc_num', models.CharField(max_length=120, verbose_name='企业来函字号')),
                ('receive_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='收文日期')),
                ('kml_file_path', models.CharField(blank=True, default='', max_length=500, verbose_name='原始KML文件路径')),
                ('is_overlap_artifact', models.BooleanField(default=False, verbose_name='是否涉及文物')),
                ('overlapped_relics_info', models.JSONField(blank=True, default=list, verbose_name='涉事文物信息')),
                ('status', models.CharField(choices=[('10_已收文', '10_已收文'), ('20_初审安全', '20_初审安全'), ('21_CHECK_OVERLAP', '21_初审涉及'), ('30_现场勘查完成', '30_现场勘查完成'), ('40_市局审批中', '40_市局审批中'), ('45_考古流转中', '45_考古流转中'), ('50_批复已收到', '50_批复已收到'), ('60_已结案归档', '60_已结案归档')], default='10_已收文', max_length=32, verbose_name='项目状态')),
                ('field_check_date', models.DateField(blank=True, null=True, verbose_name='现场勘查日期')),
                ('shanshan_request_num', models.CharField(blank=True, default='', max_length=100, validators=[django.core.validators.RegexValidator(message='县局请示文号格式应为：鄯文旅字-2026-xx号', regex='^鄯文旅字-\\d{4}-\\d+号$')], verbose_name='县局请示文号')),
                ('city_reply_num', models.CharField(blank=True, default='', max_length=120, verbose_name='市局复函文号')),
                ('archaeology_request_num', models.CharField(blank=True, default='', max_length=120, verbose_name='考古请示文号')),
                ('archaeology_report_path', models.CharField(blank=True, default='', max_length=500, verbose_name='考古调查报告路径')),
                ('region_approval_num', models.CharField(blank=True, default='', max_length=120, verbose_name='自治区文物局批复文号')),
                ('city_final_reply_num', models.CharField(blank=True, default='', max_length=120, verbose_name='市文物局最终复函号')),
                ('final_reply_to_company', models.CharField(blank=True, default='', max_length=120, verbose_name='给企业最终复函号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用地项目审批归档',
                'verbose_name_plural': '用地项目审批归档',
                'ordering': ['-receive_date', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='core_landuse_status_0d2326_idx'), models.Index(fields=['receive_date'], name='core_landuse_receive_fbc95f_idx'), models.Index(fields=['company_name'], name='core_landuse_company_3d94e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='LandUseProjectFieldPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_path', models.CharField(max_length=500, verbose_name='现场照片路径')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('project', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='field_photos', to='core.landuseprojectapproval', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '用地项目现场照片',
                'verbose_name_plural': '用地项目现场照片',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
