# Generated by ChatGPT on 2026-06-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_landuseprojectapproval_landuseprojectfieldphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandUseProjectOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='动作编码')),
                ('action_label', models.CharField(blank=True, default='', max_length=120, verbose_name='动作名称')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='动作参数')),
                ('status_before', models.CharField(blank=True, default='', max_length=32, verbose_name='操作前状态')),
                ('status_after', models.CharField(blank=True, default='', max_length=32, verbose_name='操作后状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='land_project_operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='core.landuseprojectapproval', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '用地项目流程日志',
                'verbose_name_plural': '用地项目流程日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='core_landus_project_1226b2_idx'), models.Index(fields=['action'], name='core_landus_action_09d133_idx')],
            },
        ),
    ]
