# Generated by ChatGPT on 2026-06-29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_landuseprojectoperationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='landuseprojectapproval',
            name='incoming_doc_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='企业来函日期'),
        ),
        migrations.AddField(
            model_name='landuseprojectapproval',
            name='misc_zip_path',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='杂项ZIP文件路径'),
        ),
    ]
