# Generated by ChatGPT on 2026-06-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_landuseprojectapproval_incoming_doc_date_and_misc_zip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landuseprojectapproval',
            name='incoming_doc_num',
        ),
    ]
