# Generated by Django 6.0.6 on 2026-08-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_core_heritag_heritag_26948d_idx_core_herita_heritag_634100_idx_and_more'),
    ]

    # 0024 已将索引重命名操作改为 no-op：不同环境/Django版本下自动索引名的哈希可能不一致，
    # RenameIndex 依赖的旧索引名在部分历史库上并不存在，执行时会抛出 ValueError 并回滚。
    # makemigrations 会反复检测到同一批"索引名漂移"，这里同样将其剔除，仅保留新增字段。
    operations = [
        migrations.AddField(
            model_name='landuseprojectapproval',
            name='involves_kanerjing',
            field=models.BooleanField(default=False, verbose_name='是否涉及坎儿井'),
        ),
        migrations.AddField(
            model_name='landuseprojectapproval',
            name='kanerjing_protection_plan_path',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='坎儿井保护加固方案路径'),
        ),
        migrations.AddField(
            model_name='landuseprojectapproval',
            name='protection_measures_confirmed',
            field=models.BooleanField(default=False, verbose_name='保护措施落实核实'),
        ),
        migrations.AddField(
            model_name='landuseprojectapproval',
            name='protection_measures_note',
            field=models.TextField(blank=True, default='', verbose_name='保护措施落实情况说明'),
        ),
        migrations.AddField(
            model_name='landuseprojectapproval',
            name='requires_state_council_approval',
            field=models.BooleanField(default=False, verbose_name='是否需报国务院文物行政部门'),
        ),
        migrations.AddField(
            model_name='landuseprojectapproval',
            name='state_council_approval_num',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='国务院文物行政部门批复文号'),
        ),
        migrations.AddField(
            model_name='landuseprojectapproval',
            name='water_department_opinion',
            field=models.TextField(blank=True, default='', verbose_name='水利部门意见'),
        ),
    ]
