# Generated by Django 6.0.6 on 2026-08-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_core_heritag_heritag_26948d_idx_core_herita_heritag_634100_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='heritagephoto',
            new_name='core_herita_heritag_634100_idx',
            old_name='core_heritag_heritag_26948d_idx',
        ),
        migrations.RenameIndex(
            model_name='heritagephoto',
            new_name='core_herita_heritag_22ec4a_idx',
            old_name='core_heritag_heritag_11b432_idx',
        ),
        migrations.RenameIndex(
            model_name='immovableheritage',
            new_name='core_immova_survey__bf71be_idx',
            old_name='core_immova_survey__7b071f_idx',
        ),
        migrations.RenameIndex(
            model_name='immovableheritage',
            new_name='core_immova_categor_7ef5a2_idx',
            old_name='core_immova_categor_d12a80_idx',
        ),
        migrations.RenameIndex(
            model_name='immovableheritage',
            new_name='core_immova_protect_63a2d0_idx',
            old_name='core_immova_protect_9040d5_idx',
        ),
        migrations.RenameIndex(
            model_name='immovableheritage',
            new_name='core_immova_provinc_d1279a_idx',
            old_name='core_immova_provinc_432bf2_idx',
        ),
        migrations.RenameIndex(
            model_name='landuseprojectapproval',
            new_name='core_landus_status_2ea6ef_idx',
            old_name='core_landuse_status_0d2326_idx',
        ),
        migrations.RenameIndex(
            model_name='landuseprojectapproval',
            new_name='core_landus_receive_578bc0_idx',
            old_name='core_landuse_receive_fbc95f_idx',
        ),
        migrations.RenameIndex(
            model_name='landuseprojectapproval',
            new_name='core_landus_company_466345_idx',
            old_name='core_landuse_company_3d94e8_idx',
        ),
        migrations.RenameIndex(
            model_name='landuseprojectoperationlog',
            new_name='core_landus_project_3309e1_idx',
            old_name='core_landus_project_1226b2_idx',
        ),
        migrations.RenameIndex(
            model_name='landuseprojectoperationlog',
            new_name='core_landus_action_e548a6_idx',
            old_name='core_landus_action_09d133_idx',
        ),
        migrations.AddField(
            model_name='landuseprojectapproval',
            name='involves_kanerjing',
            field=models.BooleanField(default=False, verbose_name='是否涉及坎儿井'),
        ),
        migrations.AddField(
            model_name='landuseprojectapproval',
            name='kanerjing_protection_plan_path',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='坎儿井保护加固方案路径'),
        ),
        migrations.AddField(
            model_name='landuseprojectapproval',
            name='protection_measures_confirmed',
            field=models.BooleanField(default=False, verbose_name='保护措施落实核实'),
        ),
        migrations.AddField(
            model_name='landuseprojectapproval',
            name='protection_measures_note',
            field=models.TextField(blank=True, default='', verbose_name='保护措施落实情况说明'),
        ),
        migrations.AddField(
            model_name='landuseprojectapproval',
            name='requires_state_council_approval',
            field=models.BooleanField(default=False, verbose_name='是否需报国务院文物行政部门'),
        ),
        migrations.AddField(
            model_name='landuseprojectapproval',
            name='state_council_approval_num',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='国务院文物行政部门批复文号'),
        ),
        migrations.AddField(
            model_name='landuseprojectapproval',
            name='water_department_opinion',
            field=models.TextField(blank=True, default='', verbose_name='水利部门意见'),
        ),
    ]
