# Generated by Django 6.0.6 on 2026-09-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_backfill_involves_kanerjing'),
    ]

    # 与 0024/0025 一致：跨环境自动索引名哈希可能不一致，剔除 RenameIndex 漂移，仅保留真实字段变更。
    operations = [
        migrations.AddField(
            model_name='heritagesite',
            name='body_boundary',
            field=models.TextField(blank=True, help_text='JSON 环列表：[[[lon,lat],...],...]', null=True, verbose_name='本体边界范围坐标集合'),
        ),
        migrations.AlterField(
            model_name='heritagesite',
            name='control_zone',
            field=models.TextField(blank=True, help_text='JSON 环列表：[[[lon,lat],...],...]', null=True, verbose_name='建控地带坐标集合'),
        ),
        migrations.AlterField(
            model_name='heritagesite',
            name='protection_zone',
            field=models.TextField(blank=True, help_text='JSON 环列表：[[[lon,lat],...],...]', null=True, verbose_name='保护范围坐标集合'),
        ),
    ]

