# Generated by Django 6.0.6 on 2026-09-02 03:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_heritagesite_body_boundary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # 与 0024/0025/0027 一致：跨环境自动索引名哈希漂移会导致 migrate 报错，仅保留真实模型变更。
    operations = [
        migrations.CreateModel(
            name='SipuImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('running', '进行中'), ('success', '已完成'), ('failed', '失败')], default='running', max_length=20, verbose_name='状态')),
                ('total', models.IntegerField(default=0, verbose_name='总数')),
                ('processed', models.IntegerField(default=0, verbose_name='已处理数')),
                ('matched', models.IntegerField(default=0, verbose_name='成功写入数')),
                ('unmatched_count', models.IntegerField(default=0, verbose_name='未匹配数')),
                ('no_geometry_count', models.IntegerField(default=0, verbose_name='无矢量数据数')),
                ('unmatched_items', models.JSONField(blank=True, default=list, verbose_name='未匹配明细')),
                ('no_geometry_items', models.JSONField(blank=True, default=list, verbose_name='无矢量数据明细')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '四普边界导入任务',
                'verbose_name_plural': '四普边界导入任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sipuimportjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sipu_import_jobs', to=settings.AUTH_USER_MODEL, verbose_name='发起人'),
        ),
    ]
