# Generated by Django 6.0.6 on 2026-09-02 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_sipu_import_job'),
    ]

    # 与 0024/0025/0027/0028 一致：跨环境自动索引名哈希漂移会导致 migrate 报错，仅保留真实模型变更。
    operations = [
        migrations.AddField(
            model_name='landuseprojectapproval',
            name='kml_record',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='land_projects',
                to='core.kmluploadrecord',
                verbose_name='关联KML叠加检查记录',
            ),
        ),
        migrations.AddField(
            model_name='landuseprojectapproval',
            name='spatial_check_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='空间核验时间'),
        ),
        migrations.AddField(
            model_name='landuseprojectapproval',
            name='spatial_check_threshold_m',
            field=models.PositiveIntegerField(default=50, verbose_name='空间核验阈值(米)'),
        ),
        migrations.AddField(
            model_name='landuseprojectapproval',
            name='spatial_feature_count',
            field=models.PositiveIntegerField(default=0, verbose_name='KML要素数量'),
        ),
    ]
