# Generated by Django 6.0.6 on 2026-09-02 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_land_project_kml_record'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # 与既有迁移一致：跨环境自动索引名哈希漂移会导致 migrate 报错，仅保留真实模型变更。
    operations = [
        migrations.CreateModel(
            name='LandUseProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('incoming_request', '项目方查询函'), ('county_request', '县局请示（上行文）'), ('city_reply', '市局来函/回复意见'), ('archaeology_request', '考古请示'), ('region_approval', '自治区文物局批复'), ('city_final_reply', '市文物局最终复函'), ('state_council_approval', '国务院文物行政部门批复'), ('final_reply', '给项目方复函'), ('other', '其他公文')], max_length=32, verbose_name='公文类别')),
                ('doc_num', models.CharField(blank=True, default='', max_length=120, verbose_name='公文文号')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='公文标题')),
                ('issued_date', models.DateField(blank=True, null=True, verbose_name='成文日期')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='原始文件名')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '用地项目公文档案',
                'verbose_name_plural': '用地项目公文档案',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='landuseprojectdocument',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.landuseprojectapproval', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='landuseprojectdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='land_project_documents', to=settings.AUTH_USER_MODEL, verbose_name='上传人'),
        ),
        migrations.AddIndex(
            model_name='landuseprojectdocument',
            index=models.Index(fields=['project', 'category'], name='core_landus_project_608421_idx'),
        ),
    ]
