# Generated by Django 6.0.6 on 2026-09-05 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_land_project_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('weekly', '周报'), ('monthly', '月报'), ('quarterly', '季度报'), ('yearly', '年报')], max_length=20, verbose_name='报告周期')),
                ('period_start', models.DateField(verbose_name='统计开始日期')),
                ('period_end', models.DateField(verbose_name='统计结束日期')),
                ('title', models.CharField(max_length=200, verbose_name='报告标题')),
                ('html_content', models.TextField(verbose_name='HTML报告内容')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
            ],
            options={
                'verbose_name': '业务分析报告',
                'verbose_name_plural': '业务分析报告',
                'ordering': ['-period_end', '-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('weekly', '周报'), ('monthly', '月报'), ('quarterly', '季度报'), ('yearly', '年报')], max_length=20, unique=True, verbose_name='报告周期')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('run_hour', models.PositiveSmallIntegerField(default=8, verbose_name='执行小时')),
                ('last_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='上次生成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '报告生成计划',
                'verbose_name_plural': '报告生成计划',
                'ordering': ['period'],
            },
        ),
        migrations.AddField(
            model_name='reportrecord',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='生成人员'),
        ),
        migrations.AddIndex(
            model_name='reportrecord',
            index=models.Index(fields=['period', '-period_end'], name='core_report_period_61cab3_idx'),
        ),
    ]
