# Generated by Django 6.0.6 on 2026-09-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_rename_core_heritag_heritag_26948d_idx_core_herita_heritag_634100_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landuseprojectapproval',
            name='preliminary_is_overlap_artifact',
            field=models.BooleanField(blank=True, null=True, verbose_name='初步审查是否涉及文物'),
        ),
        migrations.AddField(
            model_name='landuseprojectapproval',
            name='preliminary_kml_file_path',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='初步选址KML文件路径'),
        ),
        migrations.AddField(
            model_name='landuseprojectapproval',
            name='preliminary_overlapped_relics_info',
            field=models.JSONField(blank=True, default=list, verbose_name='初步审查涉事文物信息'),
        ),
        migrations.AddField(
            model_name='landuseprojectapproval',
            name='preliminary_project_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='初步选址项目名称'),
        ),
        migrations.AddField(
            model_name='landuseprojectapproval',
            name='preliminary_review_date',
            field=models.DateField(blank=True, null=True, verbose_name='初步选址审查回复日期'),
        ),
        migrations.AddField(
            model_name='landuseprojectapproval',
            name='preliminary_review_opinion',
            field=models.TextField(blank=True, default='', verbose_name='初步选址审查回复意见'),
        ),
        migrations.AddField(
            model_name='landuseprojectapproval',
            name='preliminary_spatial_check_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='初步选址核查时间'),
        ),
        migrations.AddField(
            model_name='landuseprojectapproval',
            name='preliminary_spatial_check_threshold_m',
            field=models.PositiveIntegerField(default=50, verbose_name='初步核验阈值(米)'),
        ),
        migrations.AddField(
            model_name='landuseprojectapproval',
            name='preliminary_spatial_feature_count',
            field=models.PositiveIntegerField(default=0, verbose_name='初步KML要素数量'),
        ),
        migrations.AlterField(
            model_name='landuseprojectapproval',
            name='status',
            field=models.CharField(choices=[('10_已收文', '10_已收文'), ('15_初步选址审查完成', '15_初步选址审查完成'), ('20_初审安全', '20_初审安全'), ('21_CHECK_OVERLAP', '21_初审涉及'), ('30_现场勘查完成', '30_现场勘查完成'), ('40_市局审批中', '40_市局审批中'), ('45_考古流转中', '45_考古流转中'), ('50_批复已收到', '50_批复已收到'), ('60_已结案归档', '60_已结案归档')], default='10_已收文', max_length=32, verbose_name='项目状态'),
        ),
    ]
