# Generated by Django 6.0.6 on 2026-09-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_landuseprojectapproval_preliminary_is_overlap_artifact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landuseprojectapproval',
            name='reuse_preliminary_materials',
            field=models.BooleanField(default=False, help_text='勾选后沿用初审项目名称和KML；正式终审仍需重新执行空间核验。', verbose_name='终审沿用初审材料'),
        ),
    ]
