# Generated by Django 6.0.6 on 2026-10-10 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_userprofile_security_questions_and_lockout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sipuimportjob',
            options={'ordering': ['-created_at'], 'verbose_name': '四普数据导入任务', 'verbose_name_plural': '四普数据导入任务'},
        ),
        migrations.AddField(
            model_name='heritagephoto',
            name='cameraman',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='摄影者'),
        ),
        migrations.AddField(
            model_name='heritagephoto',
            name='link_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='照片关联类型（四普）'),
        ),
        migrations.AddField(
            model_name='heritagephoto',
            name='photo_no',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='照片号'),
        ),
        migrations.AddField(
            model_name='heritagephoto',
            name='sipu_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='四普照片ID'),
        ),
        migrations.AddField(
            model_name='immovableheritage',
            name='body_boundary',
            field=models.JSONField(blank=True, default=list, help_text='[[[经度,纬度],...],...]，来自四普文物矢量图', verbose_name='本体范围多边形'),
        ),
        migrations.AddField(
            model_name='immovableheritage',
            name='change_type',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='变更类型代码'),
        ),
        migrations.AddField(
            model_name='immovableheritage',
            name='control_zone',
            field=models.JSONField(blank=True, default=list, verbose_name='建设控制地带多边形'),
        ),
        migrations.AddField(
            model_name='immovableheritage',
            name='county_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=12, verbose_name='县级行政区划代码'),
        ),
        migrations.AddField(
            model_name='immovableheritage',
            name='era_stat',
            field=models.JSONField(blank=True, default=list, verbose_name='年代（统计分期）代码'),
        ),
        migrations.AddField(
            model_name='immovableheritage',
            name='industries',
            field=models.JSONField(blank=True, default=list, verbose_name='所属行业、系统代码'),
        ),
        migrations.AddField(
            model_name='immovableheritage',
            name='is_single_area',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='是否单一范围'),
        ),
        migrations.AddField(
            model_name='immovableheritage',
            name='listed_catalogs',
            field=models.JSONField(blank=True, default=list, verbose_name='所列名录、规划和数据库代码'),
        ),
        migrations.AddField(
            model_name='immovableheritage',
            name='open_status',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='开放状况代码'),
        ),
        migrations.AddField(
            model_name='immovableheritage',
            name='parent_unit_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='所属文物保护单位名称'),
        ),
        migrations.AddField(
            model_name='immovableheritage',
            name='protect_measures',
            field=models.JSONField(blank=True, default=list, verbose_name='已完成保护措施代码'),
        ),
        migrations.AddField(
            model_name='immovableheritage',
            name='protection_zone',
            field=models.JSONField(blank=True, default=list, verbose_name='保护范围多边形'),
        ),
        migrations.AddField(
            model_name='immovableheritage',
            name='registration_type',
            field=models.CharField(blank=True, default='', help_text='四普封面 searchtype：新发现/复查/拆分/合并等，含义见 SipuDictItem', max_length=20, verbose_name='登记类型代码'),
        ),
        migrations.AddField(
            model_name='immovableheritage',
            name='sipu_auditor',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='四普审定人'),
        ),
        migrations.AddField(
            model_name='immovableheritage',
            name='sipu_data',
            field=models.JSONField(blank=True, default=dict, help_text='未映射为专门字段的四普登记项、自动推断字段清单与导入告警；选项含义见 SipuDictItem', verbose_name='四普补充数据'),
        ),
        migrations.AddField(
            model_name='immovableheritage',
            name='sipu_id',
            field=models.CharField(blank=True, default=None, help_text='四普系统中该文物的 culRid，用于重复导入时幂等更新', max_length=64, null=True, unique=True, verbose_name='四普系统记录ID'),
        ),
        migrations.AddField(
            model_name='immovableheritage',
            name='sipu_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='四普最近同步时间'),
        ),
        migrations.AddField(
            model_name='immovableheritage',
            name='use_purposes',
            field=models.JSONField(blank=True, default=list, verbose_name='使用用途代码'),
        ),
        migrations.AddField(
            model_name='sipuimportjob',
            name='failed_count',
            field=models.IntegerField(default=0, verbose_name='失败数'),
        ),
        migrations.AddField(
            model_name='sipuimportjob',
            name='failed_items',
            field=models.JSONField(blank=True, default=list, verbose_name='失败明细'),
        ),
        migrations.AddField(
            model_name='sipuimportjob',
            name='options',
            field=models.JSONField(blank=True, default=dict, verbose_name='导入选项'),
        ),
        migrations.AddField(
            model_name='sipuimportjob',
            name='stats',
            field=models.JSONField(blank=True, default=dict, verbose_name='导入统计'),
        ),
        migrations.AlterField(
            model_name='heritagephoto',
            name='image',
            field=models.ImageField(blank=True, help_text='建议上传JPG/PNG格式，分辨率不低于1920×1080，文件大小不超过10MB；四普导入但未下载原图时为空', upload_to='heritage_photos/%Y/%m/', verbose_name='照片文件'),
        ),
        migrations.CreateModel(
            name='HeritageConstituent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sipu_id', models.CharField(blank=True, default='', max_length=64, verbose_name='四普记录ID')),
                ('sort_order', models.IntegerField(default=0, verbose_name='序号')),
                ('constitute_type', models.CharField(default='1', max_length=10, verbose_name='构成类型')),
                ('name', models.CharField(blank=True, default='', max_length=300, verbose_name='构成名称')),
                ('category', models.CharField(blank=True, default='', max_length=20, verbose_name='构成类别代码')),
                ('number', models.CharField(blank=True, default='', max_length=50, verbose_name='数量')),
                ('area', models.CharField(blank=True, default='', max_length=50, verbose_name='面积')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('heritage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituents', to='core.immovableheritage', verbose_name='所属文物点')),
            ],
            options={
                'verbose_name': '文物构成',
                'verbose_name_plural': '文物构成',
                'ordering': ['heritage_id', 'constitute_type', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HeritageDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sipu_id', models.CharField(blank=True, default='', max_length=64, verbose_name='四普记录ID')),
                ('sort_order', models.IntegerField(default=0, verbose_name='序号')),
                ('name', models.CharField(blank=True, default='', max_length=300, verbose_name='图纸名称')),
                ('counter', models.CharField(blank=True, default='', max_length=100, verbose_name='图纸编号')),
                ('scale', models.CharField(blank=True, default='', max_length=50, verbose_name='比例尺')),
                ('drawer', models.CharField(blank=True, default='', max_length=100, verbose_name='绘制人')),
                ('draw_time', models.CharField(blank=True, default='', max_length=50, verbose_name='绘制时间')),
                ('link_type', models.CharField(blank=True, default='', max_length=20, verbose_name='图纸类型代码')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('file', models.FileField(blank=True, upload_to='heritage_sipu/drawings/%Y/%m/', verbose_name='文件')),
                ('heritage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='core.immovableheritage', verbose_name='所属文物点')),
            ],
            options={
                'verbose_name': '文物图纸',
                'verbose_name_plural': '文物图纸',
                'ordering': ['heritage_id', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HeritageMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sipu_id', models.CharField(blank=True, default='', max_length=64, verbose_name='四普记录ID')),
                ('sort_order', models.IntegerField(default=0, verbose_name='序号')),
                ('name', models.CharField(blank=True, default='', max_length=500, verbose_name='资料名称')),
                ('file_category', models.CharField(blank=True, default='', max_length=50, verbose_name='资料类型代码')),
                ('category', models.CharField(blank=True, default='', max_length=20, verbose_name='资料形式代码')),
                ('counter', models.CharField(blank=True, default='', max_length=100, verbose_name='资料编号')),
                ('number', models.CharField(blank=True, default='', max_length=50, verbose_name='数量')),
                ('save_place', models.CharField(blank=True, default='', max_length=300, verbose_name='保存地点')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('file', models.FileField(blank=True, upload_to='heritage_sipu/materials/%Y/%m/', verbose_name='文件')),
                ('heritage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.immovableheritage', verbose_name='所属文物点')),
            ],
            options={
                'verbose_name': '文物其他资料',
                'verbose_name_plural': '文物其他资料',
                'ordering': ['heritage_id', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HeritageSipuRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sipu_id', models.CharField(blank=True, default='', max_length=64, verbose_name='四普记录ID')),
                ('sort_order', models.IntegerField(default=0, verbose_name='序号')),
                ('kind', models.CharField(choices=[('special', '关联专项'), ('threesurvey', '三普对应记录')], max_length=20, verbose_name='类型')),
                ('name', models.CharField(blank=True, default='', max_length=300, verbose_name='名称')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('heritage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sipu_relations', to='core.immovableheritage', verbose_name='所属文物点')),
            ],
            options={
                'verbose_name': '四普关联记录',
                'verbose_name_plural': '四普关联记录',
                'ordering': ['heritage_id', 'kind', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SipuDictItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=40, verbose_name='四普字段')),
                ('code', models.CharField(max_length=40, verbose_name='代码')),
                ('label', models.CharField(max_length=200, verbose_name='含义')),
            ],
            options={
                'verbose_name': '四普字典项',
                'verbose_name_plural': '四普字典项',
                'ordering': ['field', 'code'],
                'unique_together': {('field', 'code')},
            },
        ),
    ]
