# Generated by Django 6.0.6 on 2026-10-10 07:57

import django.db.models.deletion
import json
from django.db import migrations, models


def backfill_registry(apps, schema_editor):
    registrations = apps.get_model('core', 'ImmovableHeritage')
    sites = apps.get_model('core', 'HeritageSite')
    alias = schema_editor.connection.alias
    for heritage in registrations.objects.using(alias).exclude(sipu_id__isnull=True).exclude(sipu_id='').iterator():
        site = sites.objects.using(alias).filter(sip_code=heritage.survey_code).first()
        if site is None:
            site = sites()
        site.registration_id = heritage.pk
        for target, source in (
            ('sip_code', 'survey_code'), ('name', 'name'), ('level', 'protection_level'),
            ('address', 'address'), ('manager', 'manager'), ('description', 'description'),
            ('longitude', 'longitude'), ('latitude', 'latitude'),
        ):
            setattr(site, target, getattr(heritage, source))
        site.category = 'GYZ' if heritage.category == 'GWZ' else heritage.category
        for name in ('body_boundary', 'protection_zone', 'control_zone'):
            rings = getattr(heritage, name)
            if not getattr(site, name):
                setattr(site, name, json.dumps(rings, ensure_ascii=False) if rings else '')
        site.save(using=alias)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_sipuimportjob_options_heritagephoto_cameraman_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritagesite',
            name='registration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registry_site', to='core.immovableheritage', verbose_name='完整文物登记档案'),
        ),
        migrations.RunPython(backfill_registry, migrations.RunPython.noop),
    ]
