# Generated by Django 6.0.6 on 2026-10-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_heritagesite_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landuseprojectapproval',
            name='shanshan_request_num',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='县局请示文号'),
        ),
    ]
