# Generated by Django 6.0.6 on 2026-10-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_landuseprojectapproval_shanshan_request_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heritagesite',
            name='level',
            field=models.CharField(choices=[('GB', '全国重点文物保护单位'), ('SB', '省（自治区、直辖市）级文物保护单位'), ('XB', '市（县）级文物保护单位'), ('DS', '尚未定级的不可移动文物')], max_length=10, verbose_name='保护级别'),
        ),
        migrations.AlterField(
            model_name='immovableheritage',
            name='survey_code',
            field=models.CharField(blank=True, default='', help_text='系统自动生成，格式：CJ-YYYY-NNNN；历史编号保持不变', max_length=50, unique=True, verbose_name='采集编号'),
        ),
        migrations.AlterField(
            model_name='landuseprojectapproval',
            name='region_approval_num',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='省级文物行政部门批复文号'),
        ),
        migrations.AlterField(
            model_name='landuseprojectdocument',
            name='category',
            field=models.CharField(choices=[('incoming_request', '项目方查询函'), ('county_request', '县局请示（上行文）'), ('city_reply', '市局来函/回复意见'), ('archaeology_request', '考古请示'), ('region_approval', '省级文物行政部门批复'), ('city_final_reply', '市文物局最终复函'), ('state_council_approval', '国务院文物行政部门批复'), ('final_reply', '给项目方复函'), ('other', '其他公文')], max_length=32, verbose_name='公文类别'),
        ),
    ]
