from django.urls import path

from core.api.views import (
    GisKmlBatchKmlContentAPIView,
    GisKmlManagementActionAPIView,
    GisKmlProcessConvertAPIView,
    GisKmlRecordKmlContentAPIView,
    GisKmlRecordsAPIView,
    GisOvkmlConvertAPIView,
    DashboardOverviewAPIView,
    HealthAPIView,
    HeritageDetailAPIView,
    HeritageMapPointsAPIView,
    HeritageSiteManageDetailAPIView,
    HeritageSiteManageExportAPIView,
    HeritageSiteManageImportAPIView,
    HeritageSiteManageListAPIView,
    HeritageStatsMetaAPIView,
    ImmovableHeritageCollectAPIView,
    ImmovableHeritageDetailAPIView,
    ImmovableHeritageExportAPIView,
    ImmovableHeritageImportAPIView,
    ImmovableHeritageListAPIView,
    InspectionDetailAPIView,
    InspectionListAPIView,
    InspectionMetaAPIView,
    InspectionStatsAPIView,
    KanerjingListAPIView,
    SystemVersionAPIView,
    SipuBoundaryImportStartAPIView,
    SipuBoundaryImportStatusAPIView,
)
from core import views as legacy_views

app_name = 'core_api'

urlpatterns = [
    path('health/', HealthAPIView.as_view(), name='health'),
    path('system/version/', SystemVersionAPIView.as_view(), name='system_version'),
    path('system/sipu-boundary-import/start/', SipuBoundaryImportStartAPIView.as_view(), name='sipu_boundary_import_start'),
    path('system/sipu-boundary-import/status/<uuid:job_id>/', SipuBoundaryImportStatusAPIView.as_view(), name='sipu_boundary_import_status'),
    path('dashboard/overview/', DashboardOverviewAPIView.as_view(), name='dashboard_overview'),
    path('heritage/map-points/', HeritageMapPointsAPIView.as_view(), name='heritage_map_points'),
    path('heritage/stats/meta/', HeritageStatsMetaAPIView.as_view(), name='heritage_stats_meta'),
    path('heritage/classification-stats/', legacy_views.heritage_classification_stats_api, name='heritage_classification_stats'),
    path('heritage/<int:site_id>/detail/', HeritageDetailAPIView.as_view(), name='heritage_detail'),
    path('heritage/<int:pk>/boundary-export/', legacy_views.heritage_boundary_export_view, name='heritage_boundary_export'),
    path('heritage/sites/', HeritageSiteManageListAPIView.as_view(), name='heritage_site_manage_list'),
    path('heritage/sites/import/', HeritageSiteManageImportAPIView.as_view(), name='heritage_site_manage_import'),
    path('heritage/sites/export/', HeritageSiteManageExportAPIView.as_view(), name='heritage_site_manage_export'),
    path('heritage/sites/<int:site_id>/', HeritageSiteManageDetailAPIView.as_view(), name='heritage_site_manage_detail'),
    path('heritage/immovable/collect/', ImmovableHeritageCollectAPIView.as_view(), name='heritage_immovable_collect'),
    path('heritage/immovable/', ImmovableHeritageListAPIView.as_view(), name='heritage_immovable_list'),
    path('heritage/immovable/import/', ImmovableHeritageImportAPIView.as_view(), name='heritage_immovable_import'),
    path('heritage/immovable/export/', ImmovableHeritageExportAPIView.as_view(), name='heritage_immovable_export'),
    path('heritage/immovable/<int:site_id>/', ImmovableHeritageDetailAPIView.as_view(), name='heritage_immovable_detail'),
    path('projects/', legacy_views.land_project_list_api, name='land_project_list'),
    path('projects/<uuid:project_id>/', legacy_views.land_project_detail_api, name='land_project_detail'),
    path('projects/create/', legacy_views.land_project_create_api, name='land_project_create'),
    path('projects/<uuid:project_id>/upload/', legacy_views.land_project_upload_api, name='land_project_upload'),
    path('projects/<uuid:project_id>/download-misc-zip/', legacy_views.land_project_download_misc_zip_api, name='land_project_download_misc_zip'),
    path('projects/<uuid:project_id>/verify-spatial-safety/', legacy_views.verify_project_spatial_safety_api, name='verify_project_spatial_safety'),
    path('projects/next-shanshan-doc/', legacy_views.land_project_next_doc_num_api, name='land_project_next_doc_num'),
    path('projects/<uuid:project_id>/workflow-action/', legacy_views.land_project_workflow_action_api, name='land_project_workflow_action'),
    path('projects/<uuid:project_id>/controls/', legacy_views.land_project_controls_api, name='land_project_controls'),
    path('projects/<uuid:project_id>/documents/generate/', legacy_views.land_project_generate_document_api, name='land_project_generate_document'),
    path('inspections/', InspectionListAPIView.as_view(), name='inspection_list'),
    path('inspections/meta/', InspectionMetaAPIView.as_view(), name='inspection_meta'),
    path('inspections/stats/', InspectionStatsAPIView.as_view(), name='inspection_stats'),
    path('inspections/<int:inspection_id>/', InspectionDetailAPIView.as_view(), name='inspection_detail'),
    path('heritage/kanerjing/', KanerjingListAPIView.as_view(), name='kanerjing_list'),
    path('gis/kml-records/', GisKmlRecordsAPIView.as_view(), name='gis_kml_records'),
    path('gis/kml-records/batch-kml-content/', GisKmlBatchKmlContentAPIView.as_view(), name='gis_kml_batch_kml_content'),
    path('gis/kml-records/<int:record_id>/kml-content/', GisKmlRecordKmlContentAPIView.as_view(), name='gis_kml_record_kml_content'),
    path('gis/kml-management/action/', GisKmlManagementActionAPIView.as_view(), name='gis_kml_management_action'),
    path('gis/kml-process-convert/', GisKmlProcessConvertAPIView.as_view(), name='gis_kml_process_convert'),
    path('gis/ovkml-convert/', GisOvkmlConvertAPIView.as_view(), name='gis_ovkml_convert'),
]
