"""
Django settings for heritage_system project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^me3znqxm6l8%m-cxs7k$=m7=eg0h_8d&kx+p88dzsz+sg#wh*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
ALLOWED_HOSTS = ['beichenhome.top', 'localhost', '127.0.0.1', '[::1]']

# 静态文件收集目录
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# CSRF 信任域名（IPv6 环境必须）
CSRF_TRUSTED_ORIGINS = ['https://beichenhome.top:9081']
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# Application definition

INSTALLED_APPS = [
    'simpleui',
    'core',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.FirstLoginPasswordChangeMiddleware',  # 首次登录密码修改提示
    'core.middleware.DeviceAutoRedirectMiddleware',  # 自动设备检测重定向
]

ROOT_URLCONF = 'heritage_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # 确保这里能找到自定义模板
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.heritage_map_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'heritage_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

import os

STATIC_URL = '/static/'
# 开发环境：指定静态文件查找目录
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
# 生产环境：collectstatic命令收集静态文件的目标目录
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menu_display': ['普查一张图', '工程评审', '自动化办公'],
    'menus': [
        {
            'name': '普查一张图',
            'icon': 'fas fa-map-marked-alt',
            'models': [
                {
                    'name': '文物点管理',
                    'icon': 'fas fa-map-pin',
                    'url': 'core/heritagesite/'
                },
                {
                    'name': '文物分布一张图',
                    'icon': 'fas fa-globe-asia',
                    'url': '/admin/heritage-map/'
                },
                {
                    'name': '遥感影像对比',
                    'icon': 'fas fa-drafting-compass',
                    'url': '/admin/heritage-map/'
                },
                {
                    'name': 'KML叠加检查',
                    'icon': 'fas fa-layer-group',
                    'url': '/admin/kml-overlay-check/'
                }
            ]
        },
        {
            'name': '工程评审',
            'icon': 'fas fa-project-diagram',
            'models': [
                {
                    'name': '工程项目管理',
                    'icon': 'fas fa-bolt',
                    'url': 'core/projectaudit/'
                },
                {
                    'name': '项目坐标核查',
                    'icon': 'fas fa-map-marker-alt',
                    'url': 'core/coordinate/'
                },
                {
                    'name': 'OVKML转换导入',
                    'icon': 'fas fa-file-csv',
                    'url': '/admin/ovkml-converter/'
                },
                {
                    'name': '项目公文导出',
                    'icon': 'fas fa-file-export',
                    'url': '/admin/export_doc/'
                }
            ]
        },
        {
            'name': '自动化办公',
            'icon': 'fas fa-file-word',
            'models': [
                {
                    'name': '巡查记录',
                    'icon': 'fas fa-camera',
                    'url': 'core/inspectionrecord/'
                }
            ]
        },
    ]
}


# 修改后台标题
SIMPLEUI_HOME_TITLE = '鄯善县文物数字化管理平台'
SIMPLEUI_LOGO = '/static/img/logo.jpg' # 使用本地logo.jpg
# 隐藏右侧的 Django 官方相关广告和链接（让界面更清爽）
SIMPLEUI_HOME_INFO = False
SIMPLEUI_HOME_QUICK = True  # 保留快速操作栏
SIMPLEUI_HOME_ACTION = False # 隐藏最近动作
SIMPLEUI_STATIC_OFFLINE = True
SIMPLEUI_DEFAULT_THEME = 'purple.css'
SIMPLEUI_CUSTOM_JS = '/static/admin/js/simpleui_custom.js'

# 自定义登录页标题
SIMPLEUI_LOGIN_TITLE = '文物管理系统 - 请登录'
# 配置自定义首页 URL 路径 - 显示统计仪表板
SIMPLEUI_HOME_PAGE = '/admin/home/'

try:
    from local_settings import *
except ImportError:
    pass