"""
Django settings for heritage_system project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import subprocess
from datetime import datetime
from zoneinfo import ZoneInfo

try:
    import environ as _django_environ  # django-environ（正确包）
except Exception:
    _django_environ = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
SETTINGS_FILE = Path(__file__).resolve()
PROJECT_TIME_ZONE = ZoneInfo('Asia/Shanghai')

if _django_environ and hasattr(_django_environ, 'Env'):
    env = _django_environ.Env()
    env_file = BASE_DIR / '.env'
    if env_file.exists():
        _django_environ.Env.read_env(env_file)
else:
    class _SimpleEnv:
        """当 django-environ 不可用时，使用最小化 env 读取兜底。"""

        def __call__(self, key, default=None):
            return os.getenv(key, default)

    env = _SimpleEnv()

SYSTEM_REGION = env('SYSTEM_REGION', default='鄯善县')
SYSTEM_NAME = env('SYSTEM_NAME', default=f'{SYSTEM_REGION}文物管理平台')
SYSTEM_VERSION_BASE = env('SYSTEM_VERSION_BASE', default='v1.3')
USE_LEGACY_ADMIN_UI = str(env('USE_LEGACY_ADMIN_UI', default='1')).lower() in ('1', 'true', 'yes', 'on')


def build_system_version():
    """优先使用 Git 最后提交时间生成版本号，失败时自动降级。"""
    try:
        result = subprocess.run(
            ['git', 'log', '-1', '--format=%ct'],
            cwd=BASE_DIR,
            check=True,
            capture_output=True,
            text=True,
            timeout=2,
        )
        timestamp = int(result.stdout.strip())
        updated_at = datetime.fromtimestamp(timestamp, tz=PROJECT_TIME_ZONE)
        return (
            f"{SYSTEM_VERSION_BASE}+{updated_at.strftime('%Y%m%d.%H%M')}",
            'git_commit',
            updated_at,
        )
    except (subprocess.SubprocessError, FileNotFoundError, ValueError, OSError):
        pass

    try:
        updated_at = datetime.fromtimestamp(SETTINGS_FILE.stat().st_mtime, tz=PROJECT_TIME_ZONE)
        return (
            f"{SYSTEM_VERSION_BASE}+{updated_at.strftime('%Y%m%d.%H%M')}",
            'settings_mtime',
            updated_at,
        )
    except OSError:
        updated_at = datetime.now(PROJECT_TIME_ZONE)
        return (
            f"{SYSTEM_VERSION_BASE}+{updated_at.strftime('%Y%m%d.%H%M')}",
            'system_time',
            updated_at,
        )


SYS_VERSION, SYS_VERSION_SOURCE, SYS_VERSION_UPDATED_AT = build_system_version()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env(
    'DJANGO_SECRET_KEY',
    default='django-insecure-^me3znqxm6l8%m-cxs7k$=m7=eg0h_8d&kx+p88dzsz+sg#wh*'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = str(env('DJANGO_DEBUG', default='0')).lower() in ('1', 'true', 'yes', 'on')
ALLOWED_HOSTS = ['beichenhome.top', 'localhost', '127.0.0.1', '[::1]']

# CSRF 信任域名 - 生产环境保持HTTPS配置
CSRF_TRUSTED_ORIGINS = ['https://beichenhome.top:9081']
FORCE_HTTPS = str(env('DJANGO_FORCE_HTTPS', default='1')).lower() in ('1', 'true', 'yes', 'on')
SECURE_SSL_REDIRECT = FORCE_HTTPS
SESSION_COOKIE_SECURE = FORCE_HTTPS
CSRF_COOKIE_SECURE = FORCE_HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# 静态文件收集目录
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

INSTALLED_APPS = [
    'core',
    'system',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',  # 启用 humanize 支持千位分隔符、友好时间显示
    'import_export',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
]

if USE_LEGACY_ADMIN_UI:
    INSTALLED_APPS.insert(0, 'simpleui')

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.DeviceAutoRedirectMiddleware',  # 自动设备检测重定向
]

ROOT_URLCONF = 'heritage_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # 确保这里能找到自定义模板
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.system_version_context',
                'core.context_processors.heritage_map_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'heritage_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

import os

STATIC_URL = '/static/'
# 开发环境：指定静态文件查找目录
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
# 生产环境：collectstatic命令收集静态文件的目标目录
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

SIMPLEUI_CONFIG = {
    'system_keep': True,  # 设置为True，系统会自动保留原有的所有菜单，即使你没定义
    'menu_display': ['文物管理', '采集管理', '日常办公', '可视化分析', '坎儿井专项', '系统设置'],
    'menus': [
        {
            'name': '首页',
            'icon': 'fas fa-home',
            'url': '/admin/',  # 指向后台首页
        },
        {
            'name': '文物管理',
            'icon': 'fas fa-university',
            'models': [
                {
                    'name': '不可移动文物',
                    'icon': 'fas fa-fw fa-book',
                    'url': 'core/heritagesite/' # 注意这里必须是 core/heritagesite/
                },
            {
                    'name': 'KML叠加检查',
                    'icon': 'fas fa-layer-group',
                    'url': '/admin/kml-overlay-check/'
                },
                {
                    'name': 'kml处理和转换',
                    'icon': 'fas fa-file-export',
                    'url': '/admin/kml-process-convert/'
                },
            ]
        },
        {
            'name': '日常办公',
            'icon': 'fas fa-tasks',
            'models': [
                {'name': '巡查记录', 'url': 'core/inspectionrecord/', 'icon': 'fas fa-camera'},
                {'name': '项目管理', 'url': '/admin/land-projects/', 'icon': 'fas fa-project-diagram'},
            ]
        },
        {
            'name': '采集管理',
            'icon': 'fas fa-clipboard-check',
            'models': [
                {
                    'name': '鄯善县不可移动文物采集',
                    'icon': 'fas fa-mobile-alt',
                    'url': '/mobile/collect/'
                },
                {
                    'name': '采集数据管理',
                    'icon': 'fas fa-database',
                    'url': 'core/immovableheritage/'
                },
                {
                    'name': '采集照片管理',
                    'icon': 'fas fa-images',
                    'url': 'core/heritagephoto/'
                },
            ]
        },
        {
            'name': '可视化分析',
            'icon': 'fas fa-chart-pie',
            'models': [
                {
                    'name': '统计仪表板',
                    'icon': 'fas fa-chart-bar',
                    'url': '/admin/heritage-dashboard/' # 统计图表页面
                },
                {
                    'name': '文物分布一张图',
                    'icon': 'fas fa-map-marked-alt',
                    'url': '/admin/heritage-map/' # 对应刚才定义的 URL
                }
            ]
        },
        {
            'name': '坎儿井专项',
            'icon': 'fas fa-water',
            'models': [
                {
                    'name': '坎儿井管理',
                    'icon': 'fas fa-list-ul',
                    'url': '/admin/kanerjing/' # 坎儿井专项管理页面
                },
                {
                    'name': '导入检查',
                    'icon': 'fas fa-check-circle',
                    'url': '/admin/kanerjing-import-check/' # 导入检查报告
                }
            ]
        },
        {
            'name': '系统设置',
            'icon': 'fas fa-cogs',
            'models': [
                {
                    'name': '用户组管理',
                    'icon': 'fas fa-users',
                    'url': 'auth/group/'
                },
                {'name': '用户管理', 'url': 'auth/user/', 'icon': 'fas fa-user-tie'},
            ]
        },
    ]
}


# 修改后台标题
SIMPLEUI_HOME_TITLE = f'{SYSTEM_NAME} ({SYS_VERSION})'
SIMPLEUI_LOGO = '/static/img/logo.jpg' # 使用本地logo.jpg
# 隐藏右侧的 Django 官方相关广告和链接（让界面更清爽）
SIMPLEUI_HOME_INFO = False
SIMPLEUI_HOME_QUICK = True  # 保留快速操作栏
SIMPLEUI_HOME_ACTION = False # 隐藏最近动作
SIMPLEUI_STATIC_OFFLINE = True
SIMPLEUI_DEFAULT_THEME = 'purple.css'
SIMPLEUI_CUSTOM_JS = '/static/admin/js/simpleui_custom.js'

# 自定义登录页标题
SIMPLEUI_LOGIN_TITLE = f'{SYSTEM_NAME} ({SYS_VERSION}) - 请登录'
# 配置自定义首页 URL 路径 - 显示统计仪表板
SIMPLEUI_HOME_PAGE = '/admin/home/'

# DRF and CORS settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

CORS_ALLOWED_ORIGINS = [
    "https://beichenhome.top:9081",
    "http://localhost:8080", # 假设的 Flutter Web 调试地址
    "http://localhost:5173", # Vue3 + Vite 本地开发地址
]
CORS_ALLOW_CREDENTIALS = True

# 未登录访问受保护页面时统一跳转到 Django Admin 登录页，避免默认 /accounts/login/ 404
LOGIN_URL = '/admin/login/'


# DEM（SRTM 30m）按需下载缓存配置
# 生产建议在 .env 中覆盖 OPENTOPO_API_KEY，避免直接写在代码库里。
OPENTOPO_API_KEY = env(
    'OPENTOPO_API_KEY',
    default='9c353db50ec8ebc18d076ce1a85e4fcc',
)
# 必须是绝对路径，默认放在项目目录下 dem_tiles。
DEM_TILES_DIR = env(
    'DEM_TILES_DIR',
    default=str((BASE_DIR / 'dem_tiles').resolve()),
)

# DEM 下载局部代理配置（仅 utils/dem_handler.py 的 OpenTopography 下载请求生效）
# 注意：若使用 socks5，需要安装 pip install "requests[socks]"
DEM_DOWNLOAD_PROXY_ENABLED = env('DEM_DOWNLOAD_PROXY_ENABLED', default=True)
DEM_DOWNLOAD_PROXY_SCHEME = env('DEM_DOWNLOAD_PROXY_SCHEME', default='socks5')  # 可切换为 http
DEM_DOWNLOAD_PROXY_HOST = env('DEM_DOWNLOAD_PROXY_HOST', default='127.0.0.1')
DEM_DOWNLOAD_PROXY_PORT = env('DEM_DOWNLOAD_PROXY_PORT', default=10808)
DEM_DOWNLOAD_PROXY_ONLY_DOMAINS = (
    'portal.opentopography.org',
)